# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='read_posts',
            field=models.ManyToManyField(related_name='profiles_read_this', to='blog.Post'),
        ),
    ]
