# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170306_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blog.Profile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='blog.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('subject', 'subscriber')]),
        ),
    ]
