# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170307_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblogdata',
            name='read_posts',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
    ]
