# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170307_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblogdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
